#!/usr/bin/python2

# Each new term in the Fibonacci sequence is generated by adding the previous two
# terms. By starting with 1 and 2, the first 10 terms will be:

#    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four
# million, find the sum of the even-valued terms.

# Answer: 4613732


x, y = 1, 2
limit = 4000000
s = 0

while 1:
    if y % 2 == 0:
        s += y

    x, y = y, x + y

    if y > limit:
        break

print(s)
